name: Deploy HTML/CSS website on Ubuntu VPS with Apache2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Apache2
        run: sudo apt-get update && sudo apt-get install -y apache2
      
      - name: Copy website files to Apache2 web root
        run: sudo cp -r ./* /var/www/html/
        
      - name: Restart Apache2
        run: sudo service apache2 restart
